name: Build R6800 zdy Firmware

on: 
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      PID_NAME: "R6800"
      images_dir: /opt/images
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt install libtool-bin gperf python3-docutils autopoint gettext
    - name: Clone source code
      run: |
        # git clone https://github.com/SilveryX/PadavanNewKernel /opt/rt-n56u
        git clone https://github.com/MeIsReallyBa/padavan-4.4 /opt/rt-n56u
        git clone https://github.com/xuy132/PadavanAutoBuild /opt/PadavanAutoBuild
        mv -f /opt/PadavanAutoBuild/R6800 /opt/rt-n56u/trunk/configs/boards/R6800
        mv -f /opt/PadavanAutoBuild/R6800.config /opt/rt-n56u/trunk/configs/templates/R6800.config
        mv -f /opt/PadavanAutoBuild/CN.dict /opt/rt-n56u/trunk/user/www/dict/CN.dict
        mv -f /opt/PadavanAutoBuild/asus_logo.png /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/asus_logo.png
        mv -f /opt/PadavanAutoBuild/defaults.h /opt/rt-n56u/trunk/user/shared/defaults.h
        mv -f /opt/PadavanAutoBuild/Makefile /opt/rt-n56u/trunk/user/www/Makefile
    - name: Run shellcheck
      run: |
        cd /opt/rt-n56u/trunk/tools
        sh ./shellcheck.sh
    - name: Prepare toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
    - name: Build Firmware
      run: |
        mkdir -p ${images_dir}
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$PID_NAME.config ] ; then
        echo "configs/templates/$PID_NAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$PID_NAME.config .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SRELAY=y/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n/g' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        ##科学上网##
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #科学上网插件，选择n后全部有关插件都不集成
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> .config #集成xray执行文件 ~4.5M
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件 ~1.2M
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config #simple-obfs混淆插件
        ##科学上网##
        ##广告管理##
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        ##DNS服务##
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config #adg DNS去AD
        ##内网穿透服务##
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
        echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config #ddnsto ~0.5M
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n" >> .config #wireguard ~10k
        ##内网穿透服务##
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config  #ALDRIVER  ~3m
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #mentohust
        
        ##流控QOS##
        echo "CONFIG_FIRMWARE_INCLUDE_SQM=y" >> .config #SQM QOS#CPU超频
        echo "CONFIG_FIRMWARE_INCLUDE_OC=y" >> .config #CPU超频开关
        echo 'CONFIG_FIRMWARE_MT7621_OC="0x372"' >> .config #此处填写对应频率的十六进制：1000Mhz=0x312 1100Mhz=0x362 1120Mhz=0x372 1200Mhz=0x3B2
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $PID_NAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: ${{ github.event_name != 'release' && success() }}
      with:
        name: Padavan-${{ env.PID_NAME }}
        path: /opt/images/*.trx
    - name: Upload images to Releases
      if: ${{ github.event_name != 'release' && success() }}
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.workflow_token }}
        file: /opt/images/*.trx
        release_name: Padavan-${{ env.PID_NAME }}
        tag: ${{ env.PID_NAME }}
        overwrite: true
        file_glob: true
